language: python
services:
    - docker

before_script:
    # dependencies
    - pip install j2cli requests
    - wget https://github.com/riotkit-org/ci-utils/archive/v2.0.0.zip -O /tmp/ci-utils.zip
    - curl "https://raw.githubusercontent.com/riotkit-org/ci-utils/master/ci-integration/travis.sh" -s | bash

    # activate ARM builds on travis
    - /opt/riotkit/utils/bin/setup-travis-arm-builds

    # authorization
    - echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "$QUAY_PASSWORD" | sudo docker login -u "$QUAY_USERNAME" --password-stdin quay.io

after_failure:
    - ./.helpers/notify.sh "${SLACK_URL}" "php-app container build failure."

jobs:
  include:
    
    - stage: Build 7.2 at arm32v7
      script:
            - make build VERSION=7.2 ARCH=arm32v7 QEMU=TRUE || (./.helpers/notify.sh "${SLACK_URL}" "Failed to build php-app:7.2-arm32v7" && exit 1);
            - make push VERSION=7.2 ARCH=arm32v7 || (./.helpers/notify.sh "${SLACK_URL}" "Failed to push php-app:7.2-arm32v7" && exit 1);
    
    - stage: Build 7.3 at arm32v7
      script:
            - make build VERSION=7.3 ARCH=arm32v7 QEMU=TRUE || (./.helpers/notify.sh "${SLACK_URL}" "Failed to build php-app:7.3-arm32v7" && exit 1);
            - make push VERSION=7.3 ARCH=arm32v7 || (./.helpers/notify.sh "${SLACK_URL}" "Failed to push php-app:7.3-arm32v7" && exit 1);
    
    - stage: Build 7.4 at x86_64
      script:
            - make build VERSION=7.4 ARCH=x86_64 QEMU=FALSE || (./.helpers/notify.sh "${SLACK_URL}" "Failed to build php-app:7.4-x86_64" && exit 1);
            - make push VERSION=7.4 ARCH=x86_64 || (./.helpers/notify.sh "${SLACK_URL}" "Failed to push php-app:7.4-x86_64" && exit 1);
    
    - stage: Build 7.2 at x86_64
      script:
            - make build VERSION=7.2 ARCH=x86_64 QEMU=FALSE || (./.helpers/notify.sh "${SLACK_URL}" "Failed to build php-app:7.2-x86_64" && exit 1);
            - make push VERSION=7.2 ARCH=x86_64 || (./.helpers/notify.sh "${SLACK_URL}" "Failed to push php-app:7.2-x86_64" && exit 1);
    
    - stage: Build 5.4 at x86_64
      script:
            - make build VERSION=5.4 ARCH=x86_64 QEMU=FALSE || (./.helpers/notify.sh "${SLACK_URL}" "Failed to build php-app:5.4-x86_64" && exit 1);
            - make push VERSION=5.4 ARCH=x86_64 || (./.helpers/notify.sh "${SLACK_URL}" "Failed to push php-app:5.4-x86_64" && exit 1);
    
    - stage: Build 7.3 at x86_64
      script:
            - make build VERSION=7.3 ARCH=x86_64 QEMU=FALSE || (./.helpers/notify.sh "${SLACK_URL}" "Failed to build php-app:7.3-x86_64" && exit 1);
            - make push VERSION=7.3 ARCH=x86_64 || (./.helpers/notify.sh "${SLACK_URL}" "Failed to push php-app:7.3-x86_64" && exit 1);
    
    - stage: Build 5.5 at x86_64
      script:
            - make build VERSION=5.5 ARCH=x86_64 QEMU=FALSE || (./.helpers/notify.sh "${SLACK_URL}" "Failed to build php-app:5.5-x86_64" && exit 1);
            - make push VERSION=5.5 ARCH=x86_64 || (./.helpers/notify.sh "${SLACK_URL}" "Failed to push php-app:5.5-x86_64" && exit 1);
    
