version: "3"

services:
    php:
        image: quay.io/riotkit/php-app:${VERSION}-${ARCH}
        environment:
            FPM_PM_MAX_CHILDREN: 10
            FPM_PM_START_SERVERS: 4
            FPM_PM_MIN_SPARE_SERVERS: 2
            FPM_PM_MAX_SPARE_SERVERS: 5
            FPM_PM_PROCSS_IDLE_TIMEOUT: 15s
        expose:
          - 9000
          - 80
